sudo: false

language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
    - TESTS_ZEND_CODE_ANNOTATION_DOCTRINE_SUPPORT=true
    - SITE_URL="https://zendframework.github.io/zend-code"
    - GH_USER_NAME="Matthew Weier O'Phinney"
    - GH_USER_EMAIL="matthew@weierophinney.net"
    - GH_REF="github.com/zendframework/zend-code.git"
    - secure: "qgUppUW+xiQunsc07EvrYK7q9j4ewsYzN2ggxxFGaF694gkZ5V29Tb9W2qCkKEdMo6vE+X65P/lOoJceyavPm39/Ka/0V461qIiYX2ZcBVFI/eeVnpwLmU/E5YHn6fFNbiwFX0o4cJdVyTrSspMTXSuiQy+9bLSevDYmbpknR476nmsF8FRGdG6GMFx0XklF1QkoERSfy+FGlqp3VYOJZ2MH7eLhXQyGBKv471kyfmyyInUMVoDN9R8mjJ4Sxyt2qaQ5661DuWRXLaWEBaNOvfZ4++jJFipPLyqIEcE2GqTl9LH3suIBd0NAfHGgdakMJuBZfW3WA/OQ208qm+++qajnI30cxKiGkFoAR2plK9P5+09JAzbivglpEIEtq9a58/I1ahjy9+4sqJYyfxUC07o+REUleJl/ojO6QQ3JI/UUBbPSa3d78Sw9i8LUmLimiYEYQK9zwO1ZdKwJYCKaiYdYS8H0IwGci9t+MqlrllMG5M6f2HRkF1Ph05sWah8QwsGrJ7yiSiILaDHn7wFNvUiN3uw09W9AotQ0AEBzdM6U6CngDPVWKHI9L1d7+txuOLwGt6j8NKHWlgA1P9rMkeMGn2+46b5AlCkUxg6cVCA8ZLpr3a5WLK2F7qTHACtP9tckEb4G3vQjM79f6Nlpewcuc7p7uHWK5Y4UkojRN+U="

matrix:
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
        - TEST_COVERAGE=true
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=locked
        - CHECK_CS=true
    - php: 7
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

before_install:
  - travis_retry composer self-update
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" && $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || true ; fi

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS satooshi/php-coveralls:^1.0 ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CHECK_CS == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then travis_retry curl -sSL https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh | bash ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer upload-coverage ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then ./zf-mkdoc-theme/deploy.sh ; fi

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#zftalk.dev"
    on_success: change
    on_failure: always
  slack:
    rooms:
      - secure: "QX0c/iGJHn1evolZxn9nrEIEldZZKy7qXq5lRTXdwH18cGI05armT7aI0GhYOd19iFum1To+954Z1kH9M4Drp+/TQTr+9RFjE8fUePbw9QYu3BGdBWE0Ls1yk4t+hCoHCpvuSnogHRyEfJqsyomFJFiApuhCjxxewlB7cIvkLGl7w6wNyKvIq/Ds+rhdNwiszhDpLu1bmKszQsMcH9ebrQQfG95CLmZS5oVZyb4/7dTfRO8MMLg7IU4KwTOaCtISKTyAlWnDGnQhCUXKXHEXKivO8pHfRrOJwGb1Om66ciO9wFB6dasz4X0ZohMX64brDzoDr9GRschVraFV4aKhCECFbrv17Ds5yoc4sV4mEUYIbCSwAAe7IjdtT+ci/aYTjrVEbHTPkEuKfIkQPM5X6LQbvhgzqpq7uhS3q4PjOPPYjT9ezmNYnLR2veIWVuQ3/OHzUX7Hh+LZ5XhuiYZlS9jWDOr+8WpEnjppvZ607m3NfLsLDHyUGYn620i0U2ibMwvAYQJPYeJo+3QyXy1llERj/Rzktu1ZY5XBVdM5X99GyqFxvcQznY1xLdQY8D4cKXPBA58K3Hqzog1qgwRaZzFDavAstvEehzdD9aD3MZFgbnR4Yxf4AcQc8FfqS8k86H3SMKx/3ZzJSEPXspD6quYVJzaV+BO1yzIXxyL3148="
    on_success: change
    on_failure: always
